repos:
  - repo: local
    hooks:
    - id: repo-agent
      name: RepoAgent
      entry: repoagent run --target-repo-path C:\\Users\\ccl\\Desktop\\RepoAgent\\DesignMode
      language: python
      pass_filenames: false # 阻止pre commit传入文件名作为参数
      types: [python] # 可以指定钩子触发的文件类型，但是目前只支持python